baseURL: https://shuyan-portfolio.netlify.app
languageCode: en-us
title: Portfolio website for Shuyan Zou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      WELCOME HERE.
    title: Hi, I'm Shuyan Zou, an MFA2022 student
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: UK
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: szou.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 75361-28831
        title: Phone
  custom_css: []
  custom_js: []
  description: Hi I'm Shuyan Zou, an LBS student
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/noisebutyourvoice/
      - icon: fa-github
        label: GitHub
        url: https://github.com/ShuyanZou
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/shuyan-z-666541196/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: data.png
        subtitle: Analytics
        title: My Pre-programme Assignment
        url: blogs/aliquam
      - image: lbs.jpg
        subtitle: Risk-return of Djia Stocks
        title: DJIA Risk/Return
        url: blogs/risk_return
      - image: city.jpg
        subtitle: Paris
        title: City Memory
        url: blogs/magna
      - image: travel.jpg
        subtitle: Sunset
        title: Traveling
        url: blogs/tempus
      - image: adventure.jpg
        subtitle: Hiking
        title: Adventure
        url: blogs/ipsum
      - image: meetyou.jpg
        subtitle: Somewhere we met.
        title: Serendipity
        url: blogs/mylove
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hi here is my website. You can get to know about me through the following list."
    title: Know about me
    url: blogs
    